#!/usr/bin/env bash
#
# ZERO -> ROOT — deploy the whole stack onto this machine.
#
#   ./scripts/deploy.sh play.example.com     # with a domain: HTTPS via Caddy
#   ./scripts/deploy.sh --no-domain          # by IP only: HTTP, see the warning it prints
#
# Idempotent: re-running rebuilds and restarts, and never overwrites an existing .env.
set -euo pipefail

cd "$(dirname "$0")/.."

RED=$'\033[0;31m'; GREEN=$'\033[0;32m'; YELLOW=$'\033[0;33m'; DIM=$'\033[2m'; OFF=$'\033[0m'
say()  { printf '%s\n' "$*"; }
ok()   { printf '%s✓%s %s\n' "$GREEN" "$OFF" "$*"; }
warn() { printf '%s!%s %s\n' "$YELLOW" "$OFF" "$*"; }
die()  { printf '%s✗ %s%s\n' "$RED" "$*" "$OFF" >&2; exit 1; }

COMPOSE_FILE=docker-compose.prod.yml
DOMAIN_ARG="${1:-}"

[ -n "$DOMAIN_ARG" ] || die "Usage: $0 <domain>   |   $0 --no-domain"

# ---------------------------------------------------------------- preflight
say "${DIM}Checking this machine…${OFF}"

command -v docker >/dev/null 2>&1 || die "Docker is not installed. See https://docs.docker.com/engine/install/"
docker info >/dev/null 2>&1 || die "Cannot talk to the Docker daemon. Is it running, and are you in the docker group (or root)?"

if docker compose version >/dev/null 2>&1; then
  COMPOSE=(docker compose)
elif command -v docker-compose >/dev/null 2>&1; then
  COMPOSE=(docker-compose)
else
  die "Docker Compose is not installed. See https://docs.docker.com/compose/install/"
fi
ok "Docker and Compose are available"

# The web client's bundler is the memory-hungry step. Under about 2 GB of RAM plus swap it
# gets killed mid-build, and the error that surfaces ("exit code 137") says nothing useful.
mem_kb=$(awk '/MemTotal/ {print $2}' /proc/meminfo)
swap_kb=$(awk '/SwapTotal/ {print $2}' /proc/meminfo)
total_mb=$(( (mem_kb + swap_kb) / 1024 ))
if [ "$total_mb" -lt 1900 ]; then
  warn "Only ${total_mb} MB of RAM + swap. The web build needs roughly 2 GB and will be"
  warn "  killed without it (you would see 'exit code 137'). Add swap first:"
  say  "    fallocate -l 2G /swapfile && chmod 600 /swapfile && mkswap /swapfile && swapon /swapfile"
  say  "    echo '/swapfile none swap sw 0 0' >> /etc/fstab"
  die  "Not enough memory to build."
fi
ok "Memory: ${total_mb} MB available for the build"

avail_mb=$(df -Pm . | awk 'NR==2 {print $4}')
[ "$avail_mb" -ge 6000 ] || warn "Only ${avail_mb} MB of disk free; the images need roughly 5 GB."

# ------------------------------------------------------------------- mode
if [ "$DOMAIN_ARG" = "--no-domain" ]; then
  USE_HTTPS=0
  PUBLIC_URL="http://$(hostname -I 2>/dev/null | awk '{print $1}')"
  warn "Running without a domain, which means without TLS."
  warn "  The session cookie will travel in clear text: anyone on the network path can read"
  warn "  it and sign in as that player. Use this to check the deployment works, then point"
  warn "  a domain here and re-run with it."
else
  USE_HTTPS=1
  DOMAIN="$DOMAIN_ARG"
  PUBLIC_URL="https://${DOMAIN}"

  # Caddy asks Let's Encrypt for a certificate on first run, and that fails unless the name
  # already resolves here. Better to say so now than to read it out of a crash loop.
  resolved=$(getent hosts "$DOMAIN" 2>/dev/null | awk '{print $1}' | head -1 || true)
  mine=$(curl -fsS --max-time 5 https://api.ipify.org 2>/dev/null || true)
  if [ -n "$resolved" ] && [ -n "$mine" ] && [ "$resolved" != "$mine" ]; then
    warn "${DOMAIN} resolves to ${resolved}, but this server appears to be ${mine}."
    warn "  Caddy will not be able to get a certificate until DNS points here."
  elif [ -z "$resolved" ]; then
    warn "${DOMAIN} does not resolve yet. Caddy needs it to, before it can get a certificate."
  else
    ok "${DOMAIN} resolves to this server"
  fi

  for port in 80 443; do
    if ss -ltn 2>/dev/null | awk '{print $4}' | grep -qE "[:.]${port}\$"; then
      die "Port ${port} is already in use. Caddy needs both 80 and 443."
    fi
  done
  ok "Ports 80 and 443 are free"
fi

# -------------------------------------------------------------------- .env
if [ -f .env ]; then
  ok ".env already exists — leaving it alone"
else
  say "${DIM}Generating .env with fresh secrets…${OFF}"
  command -v openssl >/dev/null 2>&1 || die "openssl is needed to generate secrets."
  {
    echo "# Generated by scripts/deploy.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "SESSION_SECRET=$(openssl rand -hex 32)"
    echo "LAB_MANAGER_TOKEN=$(openssl rand -hex 24)"
    echo "POSTGRES_PASSWORD=$(openssl rand -hex 24)"
    if [ "$USE_HTTPS" = "1" ]; then
      echo "DOMAIN=${DOMAIN}"
      echo "WEB_ORIGIN=${PUBLIC_URL}"
    else
      echo "WEB_ORIGIN=${PUBLIC_URL}"
      echo "SESSION_COOKIE_SECURE=false"
      echo "GAME_BIND=0.0.0.0"
      echo "GAME_PORT=80"
      echo "# DOMAIN is unset: re-run deploy.sh with a domain to switch to HTTPS."
    fi
  } > .env
  chmod 600 .env
  ok "Wrote .env (secrets generated, file is chmod 600 — keep it off version control)"
fi

# ------------------------------------------------------------------ deploy
PROFILES=()
[ "$USE_HTTPS" = "1" ] && PROFILES=(--profile https)

say ""
say "${DIM}Building. The first run takes a few minutes.${OFF}"
"${COMPOSE[@]}" -f "$COMPOSE_FILE" "${PROFILES[@]}" build

say ""
say "${DIM}Starting…${OFF}"
"${COMPOSE[@]}" -f "$COMPOSE_FILE" "${PROFILES[@]}" up -d

# ------------------------------------------------------------------ verify
say ""
say "${DIM}Waiting for the game to answer…${OFF}"
probe="http://127.0.0.1:${GAME_PORT:-8080}/api/me"
[ "$USE_HTTPS" = "1" ] || probe="http://127.0.0.1:80/api/me"

for attempt in $(seq 1 60); do
  # 401 is the expected answer from /api/me without a session: it means the app is serving.
  code=$(curl -fsS -o /dev/null -w '%{http_code}' "$probe" 2>/dev/null || true)
  if [ "$code" = "401" ]; then
    ok "The API is up"
    break
  fi
  [ "$attempt" -lt 60 ] || {
    warn "The game did not answer in 60s. Logs:"
    "${COMPOSE[@]}" -f "$COMPOSE_FILE" logs --tail 40 game
    die "Deployment did not come up cleanly."
  }
  sleep 1
done

say ""
ok "Deployed. Open ${PUBLIC_URL}"
say ""
say "${DIM}  logs:    ${COMPOSE[*]} -f ${COMPOSE_FILE} logs -f game${OFF}"
say "${DIM}  stop:    ${COMPOSE[*]} -f ${COMPOSE_FILE} down${OFF}"
say "${DIM}  update:  git pull && ./scripts/deploy.sh ${DOMAIN_ARG}${OFF}"
